name: Next.js TypeScript Blog CI/CD

on:
  push:
    branches:
      - main

env:
  NODE_ENV: production

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test with Docker
        uses: docker://node:14
        env:
          NODE_ENV: ${{ env.NODE_ENV }}
        with:
          args: sh -c "yarn install && yarn build && yarn test"
